.git
.gitignore
.gitattributes

.vscode
.idea
.vs

**/bin/
**/obj/
**/TestResults/
**/coverage/
**/coverage.cobertura.xml

*.user
*.suo
*.rsuser

.env
.env.*
!.env.example

Dockerfile
Dockerfile.dockerignore
docker-compose*.yml

README.md
*.md

.nuget/